### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by hank-bond** [anidata/palantiri#6]
Each stale branch should have its author review the code, and decide whether it's worth someone continuing (and open an issue to track) or should be deleted.

Stale branches to monitor:

- [x]  [*continuous*](https://github.com/anidata/palantiri/tree/continuous) @bmenn 
- [x]  [*sig_handler*](https://github.com/anidata/palantiri/tree/sig_handler) @danlrobertson 
- [x]  [*continuous_dlr*](https://github.com/anidata/palantiri/tree/continuous_dlr) @danlrobertson 
- [x]  [*requirement*](https://github.com/anidata/palantiri/tree/requirement) @gte620v 
- [x] [*dlr*](https://github.com/anidata/palantiri/tree/dlr) @danlrobertson

**Comment by hank-bond** [comment]
If someone with write privs wants to add labels, go ahead.

**Comment by gte620v** [comment]
I deleted `requirement`

**Comment by dlrobertson** [comment]
I don't think the `continuous` branch was ever merged...

**Comment by bmenn** [comment]
I think the idea of a crawler running continuously is a good idea, but not sure if it's useful code given the request to move to rasp #7. Also, I am inclined to deleted the branch because there are more pressing things right now to complete than worry about a continuously running scraper.

Thoughts?

**Comment by hank-bond** [comment]
@bmenn Your code doesn't seem to be incompatible with the engines moving to rasp.  Up to you as to whether or not you want to complete the work and PR it.

**Comment by bmenn** [comment]
The `continuous` branch was merged under #12.

Closing issue since all branches have been merged.
